[tox]
envlist = py{312,313,314}
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
    pylint
    mypy
allowlist_externals =
    poetry
# changedir = {toxinidir}
commands_pre =
    poetry env use {envpython}
    poetry install --with test
commands =
    #pytest tests/ -v --cov=pam --cov-report=term-missing --cov-report=html --cov-fail-under=85
    #pylint python-pam/pam --fail-under=8.0
    #mypy -p python-pam
    poetry run pytest {posargs}
    poetry run mypy -p python-pam
    poetry run pylint python-pam/pam --fail-under=8.0
extrax =
    test
passenv =
    PYTEST_*
setenv =
    VIRTUAL_ENV = {envdir}
