[tox]
envlist = py{311,312,313,314}
isolated_build = true

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
deps =
    pytest
    pytest-cov
    pylint
    mypy
commands =
    pytest {posargs}
    mypy -p python-pam
    pylint python-pam/pam --fail-under=8.0
passenv =
    PYTEST_*
